;
; Bitfield: <description>=B,<byte offset>,<bit>,<not used><default>
; Byte: <description>=U,<byte offset><min 8 bit val>,<max 8 bit val>,<default>
;
Song Playback Loops=B,0,0,0,1
Next Track When Song Ends=B,0,1,0,0
Browser Up/Down - Next/Prev Song=B,0,2,0,0
