;
; Bitfield: <description>=B,<byte offset>,<bit>,<not used><default>
; Byte: <description>=U,<byte offset><min 8 bit val>,<max 8 bit val>,<default>
;
Enable Slideshow=B,0,0,0,0
Slideshow Timer Delay (seconds)=U,1,1,60,10
