;
; Bitfield: <description>=B,<byte offset>,<bit>,<not used><default>
; Byte: <description>=U,<byte offset><min 8 bit val>,<max 8 bit val>,<default>
;
Real Tape Loading (ZX-UNO only)=B,0,0,0,0
Real Tape Inter Block Pauses=B,0,1,0,0
